# Generated by Django 4.2.23 on 2025-07-25 14:17

from django.db import migrations, models
import goroskop.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", goroskop.apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="zodiac_sign",
            field=models.IntegerField(
                choices=[
                    (1, "Aries — March 21 - April 19"),
                    (2, "Taurus — April 20 - May 20"),
                    (3, "Gemini — May 21 - June 20"),
                    (4, "Cancer — June 21 - July 22"),
                    (5, "Leo — July 23 - August 22"),
                    (6, "Virgo — August 23 - September 22"),
                    (7, "Libra — September 23 - October 22"),
                    (8, "Scorpio — October 23 - November 21"),
                    (9, "Sagittarius — November 22 - December 21"),
                    (10, "Capricorn — December 22 - January 19"),
                    (11, "Aquarius — January 20 - February 18"),
                    (12, "Pisces — February 19 - March 20"),
                ],
                default=1,
            ),
        ),
    ]
