# Generated by Django 4.2.23 on 2025-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_user_telegram_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(choices=[("EN", "English"), ("UK", "Ukrainian")], default="EN", max_length=5),
        ),
    ]
