# Generated by Django 4.2.23 on 2025-07-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_spam",
            field=models.BooleanField(default=True),
        ),
    ]
