# Generated by Django 4.2.23 on 2025-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyHoroscope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "zodiac_sign",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Aries — March 21 - April 19"),
                            (2, "Taurus — April 20 - May 20"),
                            (3, "Gemini — May 21 - June 20"),
                            (4, "Cancer — June 21 - July 22"),
                            (5, "Leo — July 23 - August 22"),
                            (6, "Virgo — August 23 - September 22"),
                            (7, "Libra — September 23 - October 22"),
                            (8, "Scorpio — October 23 - November 21"),
                            (9, "Sagittarius — November 22 - December 21"),
                            (10, "Capricorn — December 22 - January 19"),
                            (11, "Aquarius — January 20 - February 18"),
                            (12, "Pisces — February 19 - March 20"),
                        ]
                    ),
                ),
                ("text_uk", models.TextField()),
                ("text_en", models.TextField()),
            ],
            options={
                "unique_together": {("date", "zodiac_sign")},
            },
        ),
    ]
